package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Primary Accents (Clean Minimalism - Royal Blue & Accents)
val CleanBlue = Color(0xFF2563EB)
val CleanBlueDark = Color(0xFF1D4ED8)
val CleanBlueLight = Color(0xFF3B82F6)
val CleanBlueSoft = Color(0xFFEFF6FF)
val CleanBlueSoftDark = Color(0xFF1E293B)

// Red Accent for Clear
val CleanRed = Color(0xFFDC2626)
val CleanRedSoft = Color(0xFFFEF2F2)
val CleanRedSoftDark = Color(0xFF381419)
val CleanRedDark = Color(0xFFF87171)

// Dark Theme Palette (Clean Minimalism)
val DarkBg = Color(0xFF0B0E14)
val DarkSurface = Color(0xFF161B26)
val DarkSurfaceVariant = Color(0xFF1F2636)
val DarkNumKeyBg = Color(0xFF1C2333)
val DarkNumKeyText = Color(0xFFF8FAFC)
val DarkNumKeyBorder = Color(0xFF2B3448)
val DarkUtilityKeyBg = Color(0xFF252D3D)
val DarkUtilityKeyText = Color(0xFF94A3B8)
val DarkOperatorKeyBg = Color(0xFF1E293B)
val DarkOperatorKeyText = Color(0xFF60A5FA)
val DarkOperatorKeyActiveBg = Color(0xFF2563EB)
val DarkOperatorKeyActiveText = Color(0xFFFFFFFF)
val DarkTextPrimary = Color(0xFFF8FAFC)
val DarkTextSecondary = Color(0xFF94A3B8)
val DarkCardBorder = Color(0xFF2B3448)

// Light Theme Palette (Clean Minimalism)
val LightBg = Color(0xFFF7F9FB)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceVariant = Color(0xFFF1F5F9)
val LightNumKeyBg = Color(0xFFFFFFFF)
val LightNumKeyText = Color(0xFF1E293B)
val LightNumKeyBorder = Color(0xFFE2E8F0)
val LightUtilityKeyBg = Color(0xFFF1F5F9)
val LightUtilityKeyText = Color(0xFF334155)
val LightOperatorKeyBg = Color(0xFFEFF6FF)
val LightOperatorKeyText = Color(0xFF2563EB)
val LightOperatorKeyActiveBg = Color(0xFF2563EB)
val LightOperatorKeyActiveText = Color(0xFFFFFFFF)
val LightTextPrimary = Color(0xFF0F172A)
val LightTextSecondary = Color(0xFF94A3B8)
val LightCardBorder = Color(0xFFE2E8F0)
